site_name: Diego S. García
site_description: Senior Backend Developer + Python/Django

theme:
  name: material
  language: es
  logo: assets/images/logo-negative.svg
  favicon: assets/images/favicon.svg
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Activar modo claro
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Activar modo oscuro

nav:
  - Home: index.md
  - Proyectos:
      - Pendiente: proyectos/pending.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/diegosalvadorgv/
    - icon: fontawesome/brands/github
      link: https://github.com/diego-gv

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
